AWSTemplateFormatVersion: 2010-09-09
Description: |
  Some description.
Parameters:
  RootDomainName:
    Description: Domain name for your website (example.com)
    Type: String
    Default: juliafi.net
Resources:
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
      BucketName: !Sub
          - kittens.${Domain}
          - Domain: !Ref RootDomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
